### ISSUE TITLE
SuperTokens doesn't start because of mysql auth protocol

### ISSUE THREAD

**Issue by shobhit-shrivastava** [supertokens/supertokens-core#2]
I get below error with the latest version of servertokens downloaded from the website.

`What caused the crash: Failed to initialize pool: Could not connect to address=(host=localhost)(port=3306)(type=master) : Client does not support authentication protocol requested by server. plugin type was = mysql_native_password`

I have tried both caching_sha2_password and mysql_native_password protocols. Both failed.
Other mysql clients can connect just fine.

My setup:
mysql 8.0.19
Macos catalina
servertokens latest from website

**Comment by shobhit-shrivastava** [comment]
So after downgrading mysql from 8.x to 5.7 supertokens starts just fine.

**Comment by rishabhpoddar** [comment]
If you want to use MySQL version 8.x, you can add the following to the mysql configuration file:
```
[mysqld]
default-authentication-plugin=mysql_native_password
```

Alternatively, you can give `--default_authentication_plugin=mysql_native_password` to the `mysqld` command.

**Comment by rishabhpoddar** [comment]
This issue has been resolved from core version >= 2.1.X

The issue was because of a bug in the MariaDB driver which forced the usage of `mysql_native_password`. After update MariaDB driver the default auth type works.

**Comment by stephanoparaskeva** [comment]
Having the same issue with this config for postgres
```
version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: primary_auth_db_01_development
    volumes:
      - ./pgdata/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_db:
    image: supertokens/supertokens-postgresql
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_PORT: 5432
      SUPERTOKENS_HOST: auth_db
      SUPERTOKENS_PORT: 3567
      COOKIE_DOMAIN: auth_db
      REFRESH_API_PATH: /refresh
    volumes:
      - ../arch_supertokens/config.yaml:/usr/lib/supertokens/config.yaml
      - ../arch_supertokens/licenseKey:/usr/lib/supertokens/licenseKey
    depends_on:
      - db
```
