### ISSUE TITLE
Support docker healthcheck

### ISSUE THREAD

**Issue by kbzowski** [supertokens/supertokens-core#435]
## 🚀 Feature

It is common practice to delay the start of docker-compose services depending on "health check" of other services.  In most cases app should not start if supertokens is not ready. As far as I can see, supertokens do not provide the functionality to check health check. Or is it undocumented somewhere?
 
## Implementation details

It can be implemented as a http api endpoint or shell script.

**Comment by rishabhpoddar** [comment]
there is already a `/hello` API path which can be called to know if it's running. Would that work?

**Comment by kbzowski** [comment]
This will be enough. I did not noticed that api. Now I need to figure out how to implement healthcheck in docker without curl/wget or netcat available and without rebuilding image.

**Comment by kbzowski** [comment]
I figure it out. Testing:

```
    healthcheck:
       test: > 
           bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
       interval: 30s
       timeout: 15s
       retries: 3
```
