### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by stather** [supertokens/supertokens-core#517]
Container running in kubernetes that was previously fine, now refusing to start with the following error.

Tried with both latest image and 3.16. Same thing.

Loading storage layer.
Loading PostgreSQL config.
Loading supertokens config.
Stopping SuperTokens...
←[31mWhat caused the crash: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `int` from String "tcp://10.111.143.143:80": not a valid Integer
 value
 at [Source: (File); line: 175, column: 7] (through reference chain: io.supertokens.config.CoreConfig["port"])←[0m

**Comment by rishabhpoddar** [comment]
Hey. What env vars are you giving to the docker image?

**Comment by stather** [comment]
Here are the deployment manifests

supertokens-service.yaml

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: supertokens
  namespace: default
spec:
  ports:
    - name: super-http
      protocol: TCP
      port: 80
      targetPort: 3567
  selector:
    app: supertokens
  type: ClusterIP
```

supertokens-ingress.yaml

``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supertokens-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - supertokens.webuildgreatsoftware.co.za
      secretName: supertokens-secret-100
  rules:
    - host: supertokens.webuildgreatsoftware.co.za
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supertokens
                port:
                  number: 80
```


supertokens-deployment.yaml

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: supertokens
    app: supertokens
  name: supertokens
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: supertokens
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/app_network: "true"
        io.kompose.service: supertokens
        app: supertokens
    spec:
      containers:
        - env:
            - name: POSTGRESQL_CONNECTION_URI
              value: postgresql://supertokens:XXXXXXXXX@192.168.0.215:5432/supertokens
          image: registry.supertokens.io/supertokens/supertokens-postgresql
          livenessProbe:
            exec:
              command:
                - |
                  bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: supertokens
          ports:
            - containerPort: 3567
          resources: {}
      restartPolicy: Always
status: {}
```

**Comment by stather** [comment]
Turns out this was fixed by passing the port as an env var

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: supertokens
    app: supertokens
  name: supertokens
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: supertokens
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/app_network: "true"
        io.kompose.service: supertokens
        app: supertokens
    spec:
      containers:
        - env:
            - name: POSTGRESQL_CONNECTION_URI
              value: postgresql://supertokens:XXXXXXXX@192.168.0.215:5432/supertokens
            - name: SUPERTOKENS_PORT
              value: "3567"
          image: registry.supertokens.io/supertokens/supertokens-postgresql
          livenessProbe:
            exec:
              command:
                - |
                  bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: supertokens
          ports:
            - containerPort: 3567
          resources: {}
      restartPolicy: Always


```
