### ISSUE TITLE
Postgres role error

### ISSUE THREAD

**Issue by MigFerreira** [supertokens/supertokens-core#753]
## 🐛 Bug Report

Getting constant log error of **FATAL:  role "supertoken_user" does not exist**

## Useful informations

docker-compose.yml:
```yaml
version: '3.8'

services:

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://supertokens_user:somePassword@db:5432/supertokens"
    networks:
      - app_network
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5


# Note: If you are assigning a custom name to your db service on the line below, make sure it does not contain underscores
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: supertokens_user 
      POSTGRES_PASSWORD: somePassword 
      POSTGRES_DB: supertokens
    ports:
      - 5432:5432
    networks:
      - app_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'supertoken_user', '-d', 'supertokens']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge
```

screenshot:
![image](https://github.com/supertokens/supertokens-core/assets/485368/7e04304b-4f9b-47b5-9ed2-bf970611dcd3)
