### ISSUE TITLE
Logs contains the mysql password when failing to connect to the database

### ISSUE THREAD

**Issue by michael-pxr** [supertokens/supertokens-core#907]
## 🐛 Bug Report

supertokens-core logs the mysql password when failing to connect to the database.

## Useful informations

I've added to following to my `docker-compose.yml` to run supertokens-core:
```yaml
    supertokens:
        image: registry.supertokens.io/supertokens/supertokens-mysql:7.0
        container_name: supertokens
        ports:
            - '3567:3567'
        networks:
            - publishing
        environment:
            MYSQL_USER: '${MYSQL_USERNAME}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_HOST: '${MYSQL_HOST}'
            MYSQL_PORT: '3306'
            MYSQL_DATABASE_NAME: 'supertokens'
```

I have not yet created the `supertokens` database and expect supertokens-core to fail, which it does. However, I did not expect the logs to contain the mysql password. Below you can find the logs:

```text
± docker compose logs -f supertokens
supertokens  | Loading supertokens config.
supertokens  | Completed config.yaml loading.
supertokens  | Loading storage layer.
supertokens  | Loading MySQL config.
supertokens  | Loading supertokens version.yaml file.
supertokens  | 08 Jan 2024 14:15:04:929 +0000 | INFO | pid: 35671641-f174-425a-a463-1a192f6db15f | [main] thread | io.supertokens.storage.mysql.ConnectionPool.initPool(ConnectionPool.java:135) | Setting up MySQL connection pool.
supertokens  |
supertokens  | Setting up MySQL connection pool.
[this line] supertokens  | 08 Jan 2024 14:15:05:058 +0000 | ERROR | pid: 35671641-f174-425a-a463-1a192f6db15f | [main] thread | io.supertokens.storage.mysql.HikariLoggingAppender.doAppend(HikariLoggingAppender.java:132) | |my-db|3306|supertokens~|10|michael|>>>>>>>>>>>>>>>>>>>MY_PASSWORD<<<<<<<<<<<<<<<<<<<<<<<<<<|allowPublicKeyRetrieval=true|mysql - Exception during pool initialization.
supertokens  |
supertokens  | Stopping SuperTokens...
supertokens  | 08 Jan 2024 14:15:05:058 +0000 | INFO | pid: 35671641-f174-425a-a463-1a192f6db15f | [main] thread | io.supertokens.Main.stopApp(Main.java:417) | Tenant(, public, public) | Stopping SuperTokens...
supertokens  |
supertokens  | Tenant(, public, public) | What caused the crash: io.supertokens.pluginInterface.exceptions.DbInitException: java.sql.SQLException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect to address=(host=my-db)(port=3306)(type=master) : (conn=1710005) Unknown database 'supertokens'
```

I've replaced the actual password with `>>>>>>>>>>>>>>>>>>>MY_PASSWORD<<<<<<<<<<<<<<<<<<<<<<<<<<`.
